zat open float

diff --git a/.local/bin/zat-open-list-float-fullscreen b/.local/bin/zat-open-list-float-fullscreen
--- a/.local/bin/zat-open-list-float-fullscreen
+++ b/.local/bin/zat-open-list-float-fullscreen
@@ -2,35 +2,83 @@
 
 info=$(cat << EOF
 SYNOPSIS
-        zat-open-list-float-fullscreen [-s start] [-e end] [directory] [river-tag]
+        zat-open-list-float-fullscreen [-d directory] [-t tag] [-s start] [-e end]
 
 DESCRIPTION
         open a list of numbered files with zathura
         in fullscreen stacked mode with river
         directory is an optional parameter
         if not specified current directory is considered
-        river-tag is an optional parameter
-        if not specified current river-tag is considered
+        river tag is an optional parameter
+        if not specified current river tag is considered
         start and finish are two numbers (finish >= start)
         this script will open all files that start with a number
         between start and finish (start <= number <= finish)
         if start and finish are not specified
         zathura tries to open all files
 
+        -h, --help
+            print this info and exit
+
+        -d, --directory=
+            directory that contains files
+
+        -t, --tag=
+            open files in specified river tag
+
         -s, --start=
             start number
 
         -e, --end=
             end number
-
-        -h, --help
-            print this info and exit
 EOF
 )
 
-print_set_two_times() {
-    echo "error: $1 set two times\n"
+print_error() {
+    printf "error: %s\n\n" "$1"
     echo "$info"
+}
+
+print_set_two_times() {
+    print_error "$1 set two times"
+}
+
+set_option_one_dash() {
+    option="$1"
+    shift 1
+    if [ "$#" -ge 2 ]; then
+        if eval [ -z "\$$option" ]; then
+            eval "$option=$2"
+        else
+            print_set_two_times "$option"
+            return 1
+        fi
+    else
+        print_error "$option not present"
+        return 1
+    fi
+    return 0
+}
+
+set_option_two_dash() {
+    option="$1"
+    shift 1
+    if eval [ -z "\$$option" ]; then
+        eval "$option=$(echo "$1" | cut -d '=' -f '2-')"
+    else
+        print_set_two_times "$option"
+        return 1
+    fi
+}
+
+is_number() {
+    # check if parameter is a number
+    if [ "$1" -ge 0 ] > /dev/null 2>&1; then
+        return 0
+    else
+        print_error "$1 is not a number >= 0"
+        return 1
+    fi
 }
 
 open_file() {
@@ -50,83 +98,71 @@ while [ "$#" -gt 0 ]; do
             echo "$info"
             return 0
         ;;
-        -s)
-            if [ "$#" -ge 2 ]; then
-                if [ -z "$start" ]; then
-                    start="$2"
-                else
-                    print_set_two_times start
-                    return 1
-                fi
+        -d)
+            if set_option_one_dash directory "$@"; then
+                shift 1
             else
-                echo "error: start not present\n"
-                echo "$info"
                 return 1
             fi
-            shift 1
+        ;;
+        --directory=*)
+            ! set_option_two_dash directory "$@" && return 1
+        ;;
+        -t)
+            if set_option_one_dash tag "$@"; then
+                shift 1
+            else
+                return 1
+            fi
+        ;;
+        --tag=*)
+            ! set_option_two_dash tag "$@" && return 1
+        ;;
+        -s)
+            if set_option_one_dash start "$@"; then
+                shift 1
+            else
+                return 1
+            fi
         ;;
         --start=*)
-            if [ -z "$start" ]; then
-                start=$(echo "$1" | cut -d "=" -f "2-")
-            else
-                print_set_two_times start
-                return 1
-            fi
+            ! set_option_two_dash start "$@" && return 1
         ;;
         -e)
-            if [ "$#" -ge 2 ]; then
-                if [ -z "$end" ]; then
-                    end="$2"
-                else
-                    print_set_two_times end
-                    return 1
-                fi
+            if set_option_one_dash end "$@"; then
+                shift 1
             else
-                echo "error: end not present\n"
-                echo "$info"
                 return 1
             fi
-            shift 1
         ;;
         --end=*)
-            if [ -z "$end" ]; then
-                end=$(echo "$1" | cut -d "=" -f "2-")
-            else
-                print_set_two_times end
-                return 1
-            fi
+            ! set_option_two_dash end "$@" && return 1
         ;;
         *)
-            if [ -d "$1" ]; then
-                if [ -z "$directory" ]; then
-                    directory="$1"
-                else
-                    print_set_two_times directory
-                    return 1
-                fi
-            # check if parameter is a number
-            elif [ "$1" -ge 0 ] > /dev/null 2>&1; then
-                if [ -z "$tag" ]; then
-                    tag="$1"
-                else
-                    print_set_two_times river-tag
-                    echo "$info"
-                    return 1
-                fi
-            else
-                echo "error: $1 not recognized\n"
-                echo "$info"
-                return 1
-            fi
+            print_error "$1 not recognized"
+            return 1
         ;;
     esac
     shift 1
 done
 
-[ -n "$directory" ] && cd "$directory"
+if [ -n "$directory" ]; then
+    if [ -d "$directory" ]; then
+        cd "$directory" || return 1
+    else
+        print_error "$directory is not a directory"
+        return 1
+    fi
+fi
 
 program="zat"
-[ -n "$tag" ] && program="$program $tag"
+if [ -n "$tag" ]; then
+    if is_number "$tag"; then
+        program="$program $tag"
+    else
+        return 1
+    fi
+fi
 
 if [ -z "$start" ] && [ -z "$end" ]; then
     files="$(fd --type file --type symlink --exact-depth 1)"
@@ -137,9 +173,11 @@ else
     [ -z "$start" ] && start=0
     [ -z "$end" ] && end=100
 
+    ! is_number "$start" && return 1
+    ! is_number "$end" && return 1
+
     if [ "$start" -gt "$end" ]; then
-        echo "error: end should be greater than start\n"
-        echo "$info"
+        print_error "end should be greater than start"
         return 1
     fi
 
